### ISSUE TITLE
Problems to run on Linux

### ISSUE THREAD

**Issue by emmanuelframos-zz** [aecavac/spring-react-restful-example#1]
Hello my friend,

I've found two issues:
- need install axios (missing in package.json)
- need convert table names to uppercase in your script, because Linux is case sensitive

everything else is fine, congrats!

**Comment by aecavac** [comment]
Hi, thank you for feedback, i've added you as a member. You can also contribute or pull request.

**Comment by emmanuelframos-zz** [comment]
Thanks friend,

I've made two pull request to fix the issues.

Best regards.


2017-10-02 12:15 GMT-03:00 Ali Emre Cavaç <notifications@github.com>:

**Comment by aecavac** [comment]
You're welcome @emmanuelframos,
Best
